import Head from 'next/head';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { useState } from 'react';
import Image from 'next/image';
import francesavatar from '../public/francesavatar.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Frances Fogarty Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' bg-white dark:bg-gray-900'>
        <nav className='sticky top-0 z-50 bg-white dark:bg-gray-900 px-10 md:px-20 lg:px-40 py-6 flex justify-between dark:text-white shadow-sm'>
          <div className='flex items-center'>
            <Image
              src={francesavatar}
              width={40}
              height={40}
              className='rounded-full object-cover'
              alt='Frances Fogarty Logo'
            />
          </div>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className=' cursor-pointer text-2xl'
              />
            </li>
            <li>
              <a
                className='bg-gradient-to-r from-pink-500 to-rose-500 text-white px-4 py-2 border-none rounded-md ml-8'
                href='CV - Frances Femille Fogarty.pdf'
                download
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
        <section className='min-h-screen px-10 md:px-20 lg:px-40 flex items-center justify-center'>
          <div className='text-center max-w-6xl'>
            <h2 className='text-4xl py-1 text-rose-600 font-medium dark:text-rose-400 md:text-5xl'>
              Frances Femille Fogarty
            </h2>
            <h3 className='text-xl py-1 dark:text-white md:text-2xl'>
              Frontend Developer
            </h3>
            <p className='text-sm py-3 leading-relaxed text-gray-800 dark:text-gray-200 max-w-2xl mx-auto md:text-base'>
              Hello! I am Frances Fogarty, a Frontend Developer with a strong
              full-stack foundation and a passion for building accessible,
              responsive, and intuitive web interfaces. With hands-on experience
              from Klarna, Ringtail Interactive, and Integrify, I have worked
              across diverse environments from designing UI components in Unity
              to developing internal tools with React, and TypeScript. My goal
              is to create user-centered digital experiences that are both
              functional and delightful.
            </p>
            <div className='text-3xl flex justify-center gap-12 py-2 text-gray-600 dark:text-gray-400 mb-4'>
              <a
                href='https://github.com/femmiennine'
                target='_blank'
                rel='noopener noreferrer'
              >
                <AiFillGithub />
              </a>
              <a
                href='https://linkedin.com/femmiennine'
                target='_blank'
                rel='noopener noreferrer'
              >
                <AiFillLinkedin />
              </a>
            </div>
            
            <h3 className='text-lg py-2 dark:text-white'>Technical Skills</h3>
            <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3 py-2'>
              <div className='bg-white dark:bg-gray-800 p-3 rounded-lg shadow text-center hover:shadow-lg transition-shadow'>
                <h4 className='text-rose-600 font-semibold mb-1 text-sm'>Frontend</h4>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  React, Next.js
                </p>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  TypeScript, JavaScript
                </p>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  Styled Components, Tailwind CSS
                </p>
              </div>
              <div className='bg-white dark:bg-gray-800 p-3 rounded-lg shadow text-center hover:shadow-lg transition-shadow'>
                <h4 className='text-rose-600 font-semibold mb-1 text-sm'>Backend</h4>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  Node.js, Express
                </p>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  REST APIs
                </p>
              </div>
              <div className='bg-white dark:bg-gray-800 p-3 rounded-lg shadow text-center hover:shadow-lg transition-shadow'>
                <h4 className='text-rose-600 font-semibold mb-1 text-sm'>Game Dev</h4>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  Unity
                </p>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  Unity UI Toolkit
                </p>
                <p className='text-xs text-gray-600 dark:text-gray-300'>C#</p>
              </div>
              <div className='bg-white dark:bg-gray-800 p-3 rounded-lg shadow text-center hover:shadow-lg transition-shadow'>
                <h4 className='text-rose-600 font-semibold mb-1 text-sm'>Database</h4>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  MongoDB
                </p>
              </div>
              <div className='bg-white dark:bg-gray-800 p-3 rounded-lg shadow text-center hover:shadow-lg transition-shadow'>
                <h4 className='text-rose-600 font-semibold mb-1 text-sm'>Tools</h4>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  Git, GitHub
                </p>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  Docker
                </p>
                <p className='text-xs text-gray-600 dark:text-gray-300'>
                  AWS, Azure, Vercel
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className='py-10 px-10 md:px-20 lg:px-40'>
          <div>
            <h3 className='text-3xl py-1 dark:text-white '>Portofolio</h3>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1 '>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
                src={web1}
                alt='image 6'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
                src={web2}
                alt='image 3'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
                src={web3}
                alt='image 0'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
                src={web4}
                alt='image 1'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
                src={web5}
                alt='image 2'
              />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive'
                src={web6}
                alt='image 3'
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
